# Shell variables
# Generated by 'wal'
wallpaper="/home/john/wallpapers/wall.jpg"

# Special
background='#0a0c0a'
foreground='#d6c6a6'
cursor='#d6c6a6'

# Colors
color0='#0a0c0a'
color1='#6B4F39'
color2='#776438'
color3='#5E5647'
color4='#8E6039'
color5='#976D49'
color6='#779470'
color7='#d6c6a6'
color8='#958a74'
color9='#6B4F39'
color10='#776438'
color11='#5E5647'
color12='#8E6039'
color13='#976D49'
color14='#779470'
color15='#d6c6a6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
