--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/john/wallpapers/wall.jpg"

-- Special
background="#0a0c0a"
foreground="#d6c6a6"
cursor="#d6c6a6"

-- Colors
color0="#0a0c0a"
color1="#6B4F39"
color2="#776438"
color3="#5E5647"
color4="#8E6039"
color5="#976D49"
color6="#779470"
color7="#d6c6a6"
color8="#958a74"
color9="#6B4F39"
color10="#776438"
color11="#5E5647"
color12="#8E6039"
color13="#976D49"
color14="#779470"
color15="#d6c6a6"
